services:
  - type: web
    name: gigo-backend
    runtime: docker
    rootDir: gigo-backend
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: FRONTEND_DOMAIN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
